import {automaticSelection} from './flight-courier.mjs';
export const STATE_LABELS=Object.freeze({COMPLETE:'Flight complete',INCOMPLETE:'Flight incomplete',PROVISIONAL:'Unqualified / provisional',CORRUPT:'Corrupt evidence',QUALIFIED_OPEN:'Active / unavailable'});
export const INTEGRITY_LABELS=Object.freeze({1:'Verified',2:'Torn tail preserved',3:'Corrupt evidence preserved'});
const decimal=v=>typeof v==='string'&&/^(0|[1-9][0-9]{0,19})$/.test(v)?BigInt(v):0n;
export function runtimeText(us){const minutes=decimal(us)/60000000n;return (minutes/60n).toString().padStart(2,'0')+':'+(minutes%60n).toString().padStart(2,'0');}
export function timeText(utc){const seconds=decimal(utc);if(seconds===0n)return 'Time unknown';if(seconds>8640000000000n)return 'Time outside display range';return new Date(Number(seconds)*1000).toISOString().replace('T',' ').slice(0,16)+' UTC';}
export function capacity(count){if(!Number.isInteger(count)||count<0||count>64)return {level:'unknown',text:'Capacity unknown'};const level=count===64?'full':count>=60?'critical':count>=56?'warning':'normal';return {level,text:level==='normal'?'':level.toUpperCase()+' — Transferring does not free Flight Log capacity.'};}
export function connectionError(code){if(['REPAIR_REQUIRED','AUTH_REQUIRED','INVALID_TOKEN','TOKEN_REVOKED','CREDENTIAL_UNAVAILABLE'].includes(code))return {state:'REPAIR_REQUIRED',message:'Re-pair required. Pairing may have expired after HuginnEIS restart.'};if(/SOURCE_DEVICE|DEVICE_MISMATCH|SOURCE_ID/.test(code))return {state:'DEVICE_MISMATCH',message:'Device identity mismatch. Check the paired HuginnEIS.'};if(/TLS|CERT|SPKI|SAN|TRUST|PRODUCTION_TRUST/.test(code))return {state:'TLS_ERROR',message:'Secure connection could not be verified. Check pairing and phone time.'};if(['LOCAL_NETWORK_DENIED','PERMISSION_DENIED'].includes(code))return {state:'LOCAL_NETWORK_DENIED',message:'Allow HuginnAPP local network access in phone settings.'};return {state:'PAIRED_OFFLINE',message:code==='RETRYABLE_503'?'Temporary HuginnEIS busy — Retry available':'Local network unavailable. Connect phone to HuginnEIS Wi-Fi; retry available.'};}
export function durableText(status={}){if(status.conflict)return 'CONFLICT — Both evidence identities retained; ACK blocked';if(status.state==='SOURCE_CHANGED')return 'SOURCE_CHANGED — Evidence changed since this download began; ACK blocked';if(status.state==='VERIFYING')return 'VERIFYING — Checking stored evidence';if(status.state==='STORED_LOCAL')return 'STORED_LOCAL — Awaiting verification';if(status.state==='FAILED_RETRYABLE')return 'FAILED_RETRYABLE — Retry available';if(status.state==='REPAIR_REQUIRED')return 'REPAIR_REQUIRED — Re-pair required';if(status.ack_status==='ACKED')return 'ACKED — Transferred (device ACK accepted)';if(status.state==='IMPORTED'){if(status.ack_status==='PENDING'||status.ack_status==='OUTCOME_UNKNOWN')return 'ACK_PENDING — Stored locally — ACK pending'+(status.ack_status==='OUTCOME_UNKNOWN'?' (previous response unknown)':'');return 'IMPORTED — Stored locally';}return 'DOWNLOADING — Committed local progress';}
export function progress(status){const offset=decimal(status.offset),size=decimal(status.physical_bytes);const committed=offset>size?size:offset;return {offset:committed.toString(),size:size.toString(),percent:size>0n?Number(committed*10000n/size)/100:0};}
export function selection(m){if(automaticSelection(m))return 'automatic';if(m.eligible===true&&m.state==='PROVISIONAL'&&m.reason==='OWNER_SELECTION_REQUIRED_PROVISIONAL')return 'provisional';if(m.eligible===true&&m.state==='CORRUPT'&&m.integrity===3&&m.reason==='OWNER_SELECTION_REQUIRED_FORENSIC')return 'forensic';return 'unavailable';}
function safe(value,depth=0){if(depth>8||ArrayBuffer.isView(value)||value instanceof ArrayBuffer)throw Error('BRIDGE_PRIVACY');if(Array.isArray(value)){if(value.length>64)throw Error('BRIDGE_LIMIT');value.forEach(v=>safe(v,depth+1));}else if(value&&typeof value==='object')for(const [key,v]of Object.entries(value)){if(/token|authorization|secret|bytes_base64|raw_evidence|private_key/i.test(key))throw Error('BRIDGE_PRIVACY');safe(v,depth+1);}return value;}
export function mountCourierUI(doc,native,transport){const el=id=>doc.getElementById('courier-'+id),state={pairs:[],ref:null,connection:'UNPAIRED',message:'Pairing required',queue:[],local:[],full:false,count:null,busy:false,operation:null};let subscription;
  const text=(id,value)=>{el(id).textContent=value;};const element=(name,value)=>{const e=doc.createElement(name);if(value!==undefined)e.textContent=value;return e;};
  const call=async(op,args={})=>{if(!native||typeof native[op]!=='function')throw Error('NATIVE_COURIER_UNAVAILABLE');const result=safe(await native[op](Object.freeze({...args})));if(JSON.stringify(result).length>65536)throw Error('BRIDGE_LIMIT');return result;};
  function row(metadata,status,local){const li=element('li');li.dataset.session=metadata.session_id||'';li.append(element('strong',timeText(metadata.start_utc)),element('p',(metadata.state||'Unknown')+' — '+(STATE_LABELS[metadata.state]||'Unavailable evidence')),element('p','Flight time '+runtimeText(metadata.runtime_us)),element('p',INTEGRITY_LABELS[metadata.integrity]||'Integrity unavailable'));if(metadata.integrity!==1)li.classList.add('courier-warning');li.append(element('p',local?'Source device: '+metadata.source_device_id:'Owner action: '+(selection(metadata)==='automatic'?'Automatic candidate':selection(metadata)==='unavailable'?'Unavailable':'Explicit confirmation required')));li.append(element('p',status?durableText(status):metadata.transfer_state==='TRANSFERRED'?'Device reports TRANSFERRED':'Not transferred'));
    if(status){const p=progress(status),bar=element('progress');bar.max=100;bar.value=p.percent;bar.setAttribute('aria-label','Committed SQLite transfer progress');li.append(bar,element('p',p.offset+' / '+p.size+' committed bytes · '+p.percent+'%'));}
    if(!local){const kind=selection(metadata),button=element('button',kind==='forensic'?'Review forensic transfer':kind==='provisional'?'Review provisional transfer':'Transfer / resume');button.type='button';button.disabled=state.busy||!state.ref||state.connection!=='CONNECTED'||kind==='unavailable'||status?.conflict||status?.state==='SOURCE_CHANGED';button.setAttribute('aria-label',button.textContent+' '+(metadata.session_id||'unavailable'));button.addEventListener('click',()=>run(()=>transfer(metadata)));li.append(button);}
    const detail=element('details'),summary=element('summary','Diagnostics');detail.append(summary);const fields={session:metadata.session_id,filename:metadata.filename,physical_bytes:metadata.physical_bytes,reason:metadata.reason,hash:metadata.metadata_sha256?.slice(0,12),manifest_generation:metadata.manifest_generation};for(const [key,value]of Object.entries(fields))if(value!==null&&value!==undefined)detail.append(element('p',key+': '+value));li.append(detail);return li;}
  function render(){text('connection',state.connection+' — '+state.message);const pair=state.pairs.find(p=>p.paired_ref===state.ref);text('peer',pair?'Trust profile: '+pair.trust_profile+' · Leaf fingerprint: '+pair.fingerprint:'Unpaired');text('summary','Flights: '+(state.queue.length?state.queue.filter(m=>m.transfer_state!=='TRANSFERRED').length:state.count===0?0:'unknown')+' waiting · Storage: '+(state.count??'unknown')+'/64');const cap=capacity(state.count);text('capacity',cap.text);el('capacity').className=cap.text?'courier-warning':'';text('gate',state.full?'Native ACK gate passed for this phone/build':'ACK unavailable until this phone/build is qualified');el('ack').disabled=!state.full||state.busy||state.connection!=='CONNECTED';for(const id of ['pair','refresh','auto'])el(id).disabled=state.busy||(id!=='pair'&&!state.ref)||(id==='auto'&&state.connection!=='CONNECTED');el('cancel').disabled=!state.busy;el('device').disabled=state.busy||state.pairs.length<2;el('queue').replaceChildren(...state.queue.map(m=>row(m,state.local.find(s=>s.metadata.source_device_id===m.source_device_id&&s.metadata.session_id===m.session_id),false)));el('local').replaceChildren(...state.local.map(s=>row(s.metadata,s,true)));el('more').hidden=state.local.length===0||state.local.length%16!==0;el('more').disabled=state.busy;}
  async function loadLocal(append=false){const after=append?state.local.at(-1)?.evidence_ref||'':'';const r=await call('courierLocalList',{after});state.local=append?[...state.local,...r.evidence]:r.evidence;}
  async function discover(){const r=await call('courierPairs');state.pairs=r.pairs;state.ref=state.pairs.some(p=>p.paired_ref===state.ref)?state.ref:state.pairs[0]?.paired_ref||null;el('device').replaceChildren(...state.pairs.map(p=>{const option=element('option',p.source_device_id);option.value=p.paired_ref;return option;}));el('device').value=state.ref||'';state.connection=state.pairs.find(p=>p.paired_ref===state.ref)?.state||'UNPAIRED';state.message=state.ref?'Connect phone to HuginnEIS Wi-Fi':'Pairing required';state.full=false;}
  function error(e){const code=typeof e?.code==='string'?e.code:typeof e?.message==='string'?e.message:'';if(code==='CANCELLED'||code==='FOREGROUND_REQUIRED'||code==='FOREGROUND_CANCELLED'){text('action','Transfer stopped. Committed evidence retained.');return;}if(code==='SOURCE_CHANGED'||code==='EVIDENCE_CHANGED'||code==='CONFLICT'){text('action','SOURCE_CHANGED — Evidence changed since this download began. Existing evidence retained; ACK blocked.');state.full=false;return;}if(code==='MOBILE_QUALIFICATION_REQUIRED'){state.full=false;text('action','ACK unavailable until this phone/build is qualified');return;}if(/^(LOCAL_|CHUNK_|PHYSICAL_|PARSED_METADATA|INCOMPLETE_DOWNLOAD|TRANSPORT_OR_STORAGE_FAILURE)/.test(code)&&code!=='LOCAL_NETWORK_DENIED'){text('action','FAILED_RETRYABLE ? Check phone storage and retry. Committed evidence retained.');state.full=false;return;}const c=connectionError(code);state.connection=c.state;state.message=c.message;state.full=false;text('action','FAILED_RETRYABLE — '+c.message);}
  async function run(fn){if(state.busy)return;state.busy=true;render();try{await fn();}catch(e){error(e);}finally{try{await loadLocal();}catch{ /* Retain already shown offline metadata. */ }state.busy=false;state.operation=null;render();}}
  async function refresh(){if(!state.ref)return;state.connection='CONNECTING';state.message='Connecting to HuginnEIS';state.full=false;render();const c=await transport.connectionStatus(state.ref);if(c.state==='REPAIR_REQUIRED'){state.connection='REPAIR_REQUIRED';state.message='Re-pair required';return;}const list=await transport.listFlights(state.ref);const verified=await transport.connectionStatus(state.ref);state.full=verified.FULL_ACK_GATE_PASS===true;state.queue=[...list.entries].sort((a,b)=>(a.session_id||'').localeCompare(b.session_id||'')||a.filename.localeCompare(b.filename));state.count=state.queue.length;state.connection='CONNECTED';state.message='HuginnEIS connected';text('action','Queue refreshed');}
  async function transfer(m){const kind=selection(m);if(kind==='unavailable')throw Error('OWNER_SELECTION_REQUIRED');state.operation=m.session_id;const result=kind==='automatic'?await transport.downloadEvidence(state.ref,m.session_id):await call('courierOwnerTransfer',{paired_ref:state.ref,session_id:m.session_id});text('action',durableText(result));await loadLocal();}
  el('pair').addEventListener('click',()=>run(async()=>{await call('courierPairManual');await discover();state.queue=[];state.count=null;text('action','Paired. Connect phone to HuginnEIS Wi-Fi.');}));el('refresh').addEventListener('click',()=>run(refresh));el('auto').addEventListener('click',()=>run(async()=>{for(const m of state.queue.filter(automaticSelection)){if(state.operation==='CANCELLED')break;await transfer(m);}text('action','Selected evidence checked. See each local ACK status.');}));el('ack').addEventListener('click',()=>{if(state.full&&state.connection==='CONNECTED')run(async()=>{await transport.retryPendingAcks(state.ref);text('action','Native ACK retry finished');});});el('cancel').addEventListener('click',async()=>{state.operation='CANCELLED';try{await transport.cancelForegroundTransfer();}catch{ }text('action','Cancelled. Committed evidence retained.');});el('device').addEventListener('change',()=>{state.ref=el('device').value;state.queue=[];state.count=null;state.full=false;state.connection=state.pairs.find(p=>p.paired_ref===state.ref)?.state||'UNPAIRED';state.message='Connect phone to HuginnEIS Wi-Fi';render();});el('more').addEventListener('click',async()=>{if(state.busy)return;state.busy=true;render();try{await loadLocal(true);}catch(e){error(e);}finally{state.busy=false;render();}});
  const ready=(async()=>{if(!native){state.message='Pairing required. Open the packaged HuginnAPP on your phone.';el('pair').disabled=true;render();el('pair').disabled=true;return;}try{await discover();await loadLocal();subscription=await transport.subscribeProgress(s=>{safe(s);const old=state.local.find(r=>r.evidence_ref===s.evidence_ref);if(old){if(decimal(s.offset)>=decimal(old.offset))Object.assign(old,s);}else{const m=state.queue.find(m=>s.evidence_ref?.includes('|'+m.session_id+'|'));if(m)state.local.push({...s,metadata:m});}render();});}catch(e){error(e);}render();})();
  return Object.freeze({ready,refresh:()=>run(refresh),dispose:()=>subscription?.remove(),snapshot:()=>structuredClone(state)});
}
