import {mountCourierUI} from '/courier-ui.mjs';import {createFlightCourier} from '/flight-courier.mjs';
export async function run(){const results=[];const test=async(name,fn)=>{try{await fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:String(e),stack:e.stack});}};const eq=(a,b)=>{if(a!==b)throw Error(JSON.stringify(a)+' != '+JSON.stringify(b));},ok=v=>{if(!v)throw Error('assertion');};const template=new DOMParser().parseFromString(await(await fetch('/')).text(),'text/html').getElementById('flight-courier');let current;
const ref='paired-'+'a'.repeat(32),device='AA:BB:CC:DD:EE:FF';const metadata=(state='COMPLETE',i=1)=>({session_id:i.toString(16).padStart(32,'0'),source_device_id:device,start_utc:'0',runtime_us:'18060000000',state,complete:state==='COMPLETE',integrity:state==='CORRUPT'?3:1,eligible:state!=='QUALIFIED_OPEN',reason:state==='PROVISIONAL'?'OWNER_SELECTION_REQUIRED_PROVISIONAL':state==='CORRUPT'?'OWNER_SELECTION_REQUIRED_FORENSIC':state==='QUALIFIED_OPEN'?'ACTIVE_FLIGHT':'AUTOMATIC',filename:'F000001.FLG',physical_bytes:'32768',metadata_sha256:'a'.repeat(64),transfer_state:'NOT_TRANSFERRED'});const q=id=>document.getElementById('courier-'+id);const wait=()=>new Promise(r=>setTimeout(r,0));const settled=async()=>{for(let n=0;n<50&&current.ui.snapshot().busy;n++)await wait();};
async function setup({paired=true,queue=[metadata()],local=[],error=null}={}){if(current){await current.ui.dispose();document.getElementById('flight-courier').remove();}document.body.append(template.cloneNode(true));const calls=[],native={courierPairs:async()=>({pairs:paired?[{paired_ref:ref,source_device_id:device,state:'PAIRED_OFFLINE',fingerprint:'abcdef012345',trust_profile:'DEVELOPMENT'}]:[]}),courierLocalList:async()=>({evidence:local}),courierPairManual:async()=>{calls.push('pair');return {paired_ref:ref,source_device_id:device,state:'PAIRED'};},courierConnection:async()=>({state:'PAIRED',FULL_ACK_GATE_PASS:false}),courierList:async()=>{if(error)throw Error(error);return {entries:queue};},courierDownload:async o=>{calls.push(o.session_id);const m=queue.find(m=>m.session_id===o.session_id),r={evidence_ref:device+'|'+m.session_id+'|'+m.metadata_sha256,offset:'32768',physical_bytes:'32768',state:'IMPORTED',ack_status:'PENDING',metadata:m};local.push(r);return r;},courierOwnerTransfer:async o=>{calls.push('owner:'+o.session_id);return {state:'IMPORTED',ack_status:'PENDING'};},courierRetryAcks:async()=>{calls.push('ack');return {};},courierCancel:async()=>({state:'CANCELLED'}),addListener:async(n,fn)=>{native.progress=fn;return {remove:async()=>{}};}};const ui=mountCourierUI(document,native,createFlightCourier(native));current={ui,native,calls,queue,local};await ui.ready;return current;}
await test('unpaired DOM',async()=>{await setup({paired:false});ok(q('connection').textContent.includes('UNPAIRED'));ok(q('refresh').disabled);});
await test('paired offline',async()=>{await setup();ok(q('connection').textContent.includes('PAIRED_OFFLINE'));});
await test('connected only after list',async()=>{await current.ui.refresh();ok(q('connection').textContent.includes('CONNECTED'));});
await test('manual only opaque native action',async()=>{q('pair').click();await settled();eq(current.calls[0],'pair');eq(document.querySelectorAll('#flight-courier textarea,#flight-courier input').length,0);});
await test('QR disabled no camera action',async()=>{ok(q('scan').disabled);});
await test('all state labels and selection policy',async()=>{await setup({queue:['COMPLETE','INCOMPLETE','PROVISIONAL','CORRUPT','QUALIFIED_OPEN'].map((s,i)=>metadata(s,i+1))});await current.ui.refresh();for(const label of ['Flight complete','Flight incomplete','Unqualified / provisional','Corrupt evidence','Active / unavailable'])ok(q('queue').textContent.includes(label));ok(q('queue').lastElementChild.querySelector('button').disabled);});
await test('automatic action only two candidates',async()=>{q('auto').click();await settled();eq(current.calls.length,2);});
await test('provisional explicit native owner flow',async()=>{q('queue').children[2].querySelector('button').click();await settled();ok(current.calls.at(-1).startsWith('owner:'));});
await test('corrupt explicit forensic flow',async()=>{q('queue').children[3].querySelector('button').click();await settled();ok(current.calls.at(-1).startsWith('owner:'));ok(q('queue').textContent.includes('Corrupt evidence preserved'));});
await test('runtime and unknown time',async()=>{ok(q('queue').textContent.includes('05:01'));ok(q('queue').textContent.includes('Time unknown'));});
await test('progress committed only',async()=>{const m=metadata();await setup();await current.ui.refresh();current.native.progress({evidence_ref:device+'|'+m.session_id+'|'+m.metadata_sha256,offset:'16384',physical_bytes:'32768',state:'STAGING',ack_status:'NONE'});ok(q('local').textContent.includes('16384 / 32768'));eq(q('local').querySelector('progress').value,50);});
await test('regressive offset never advances or rolls back',async()=>{const row=current.ui.snapshot().local[0];current.native.progress({...row,offset:'0'});eq(q('local').querySelector('progress').value,50);});
await test('native verification phase',async()=>{const row=current.ui.snapshot().local[0];current.native.progress({...row,offset:'32768',state:'VERIFYING'});ok(q('local').textContent.includes('VERIFYING'));});
await test('offline imported ACK pending visible',async()=>{const m=metadata('INCOMPLETE'),local=[{metadata:m,evidence_ref:device+'|'+m.session_id+'|'+m.metadata_sha256,offset:'32768',physical_bytes:'32768',state:'IMPORTED',ack_status:'PENDING'}];await setup({local});ok(q('local').textContent.includes('Stored locally — ACK pending'));ok(q('local').textContent.includes('Flight incomplete'));});
await test('ACKED distinct from pending',async()=>{current.local[0].ack_status='ACKED';await current.ui.refresh();ok(q('local').textContent.includes('ACKED — Transferred'));});
await test('empty qualification disables ACK button',async()=>{ok(q('ack').disabled);q('ack').click();ok(!current.calls.includes('ack'));ok(q('gate').textContent.includes('until this phone/build is qualified'));});
for(const [code,label]of [['INVALID_TOKEN','REPAIR_REQUIRED'],['TOKEN_REVOKED','REPAIR_REQUIRED'],['SPKI_MISMATCH','TLS_ERROR'],['LOCAL_NETWORK_DENIED','LOCAL_NETWORK_DENIED'],['SOURCE_DEVICE_MISMATCH','DEVICE_MISMATCH'],['RETRYABLE_503','Temporary HuginnEIS busy']])await test('safe error '+code,async()=>{await setup({error:code});await current.ui.refresh();ok(q('connection').textContent.includes(label));});
await test('conflict and source changed preserved',async()=>{const m=metadata(),local=[{metadata:m,evidence_ref:device+'|'+m.session_id+'|'+m.metadata_sha256,offset:'16384',physical_bytes:'32768',state:'SOURCE_CHANGED',ack_status:'PENDING'}];await setup({local});await current.ui.refresh();ok(q('local').textContent.includes('Evidence changed'));ok(q('queue').querySelector('button').disabled);});
for(const [n,label]of [[56,'WARNING'],[60,'CRITICAL'],[64,'FULL']])await test('capacity '+n,async()=>{await setup({queue:Array.from({length:n},(_,i)=>metadata('COMPLETE',i+1))});await current.ui.refresh();ok(q('summary').textContent.includes(n+'/64'));ok(q('capacity').textContent.includes(label));ok(q('capacity').textContent.includes('does not free Flight Log capacity'));});
await test('XSS is text only',async()=>{const m=metadata();m.filename='<img src=x onerror=alert(1)>';await setup({queue:[m]});await current.ui.refresh();eq(q('queue').querySelectorAll('img').length,0);ok(q('queue').querySelector('details').textContent.includes('<img'));});
await test('no secrets accepted from native',async()=>{current.native.courierPairManual=async()=>({token:'synthetic-secret'});q('pair').click();await settled();ok(!document.body.textContent.includes('synthetic-secret'));});
await test('phone widths no horizontal scroll; touch targets labelled',async()=>{for(const width of [320,390,430]){document.body.style.width=width+'px';await wait();if(document.body.scrollWidth>width)throw Error('overflow '+width+': '+document.body.scrollWidth);for(const button of document.querySelectorAll('#flight-courier button'))if(!button.hidden&&button.getBoundingClientRect().height<44)throw Error('small button '+button.id);}ok(q('local').getAttribute('class').includes('courier-list'));});
document.body.style.width='390px';await setup({queue:['COMPLETE','INCOMPLETE','PROVISIONAL','CORRUPT','QUALIFIED_OPEN'].map((s,i)=>metadata(s,i+1)),local:[{metadata:metadata('INCOMPLETE',2),evidence_ref:device+'|'+metadata('INCOMPLETE',2).session_id+'|'+'a'.repeat(64),offset:'32768',physical_bytes:'32768',state:'IMPORTED',ack_status:'PENDING'}]});await current.ui.refresh();
return {synthetic:true,results,passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length};}
