import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';
import {runLocalFixtures} from '../mobile/fixture-runner.mjs';
import {SqliteHost,stagingOptions} from './flight-sqlite-host.mjs';import {fixture} from './flight-fixtures.mjs';import {createCourierBridge,OPERATIONS} from '../flight-mobile.mjs';
function setup(options){const dir=mkdtempSync(join(tmpdir(),'huginn-mobile-'));const store=new SqliteHost(join(dir,'evidence.sqlite'),options),api=createCourierBridge(store.bridge(OPERATIONS));return {store,api,dir,cleanup(){store.close();rmSync(dir,{recursive:true,force:true});}};}
async function stage(ctx,f=fixture()){ctx.store.register(f.metadata);const s=await ctx.api.evidenceCreateStaging(stagingOptions(f.metadata));return s.evidence_ref;}
async function chunks(ctx,e,f){for(let o=0;o<f.raw.length;o+=16384)await ctx.api.evidenceCommitRange({evidence_ref:e,offset:String(o),bytes_base64:f.raw.subarray(o,o+16384).toString('base64')});}
async function imported(ctx,f=fixture()){const e=await stage(ctx,f);await chunks(ctx,e,f);await ctx.api.evidenceImport({evidence_ref:e});return e;}
async function withStore(fn,options){const c=setup(options);try{await fn(c);}finally{c.cleanup();}}
test('bridge operations are explicit, unavailable browser fails closed',async()=>{assert.equal(OPERATIONS.length,14);await assert.rejects(createCourierBridge().platformInfo(),/UNAVAILABLE/);});
test('caller cannot supply storage authority or secret',async()=>{let calls=0;const api=createCourierBridge({storageQualification:()=>{calls++;}});for(const key of ['durable','token','secret','eligible','qualified','sql'])await assert.rejects(api.storageQualification({[key]:true}),/FORBIDDEN/);assert.equal(calls,0);});
test('bridge range and request bounds',async()=>{let calls=0;const api=createCourierBridge({evidenceCommitRange:()=>calls++,evidenceReadRange:()=>calls++});await assert.rejects(api.evidenceCommitRange({bytes_base64:Buffer.alloc(16385).toString('base64')}),/RANGE_LIMIT/);await assert.rejects(api.evidenceReadRange({length:16385}),/RANGE_LIMIT/);await assert.rejects(api.evidenceCommitRange({bytes_base64:'%%%'}),/RANGE_LIMIT/);assert.equal(calls,0);});
test('full ACK true response rejected',async()=>{await assert.rejects(createCourierBridge({storageQualification:()=>({FULL_ACK_GATE_PASS:true})}).storageQualification(),/FULL_ACK_FORBIDDEN/);});
test('real SQLite durability readback DELETE/EXTRA',()=>withStore(async c=>{const g=await c.api.storageQualification();assert.equal(g.journal_mode,'delete');assert.equal(g.synchronous,3);assert.ok(g.checks.probe_reopen_exact);assert.ok(g.sqlite_version);}));
test('exact binary BLOB round-trip',()=>withStore(async c=>{const f=fixture(),e=await stage(c,f);await chunks(c,e,f);const r=await c.api.evidenceReadRange({evidence_ref:e,offset:'0',length:f.raw.length});assert.deepEqual(Buffer.from(r.bytes_base64,'base64'),f.raw);}));
test('multi-chunk exact bytes including cross-boundary read',()=>withStore(async c=>{const f=fixture('complete',{samples:240,runtime:400000000n}),e=await stage(c,f);await chunks(c,e,f);assert.deepEqual(c.store.read(e,16300,200),f.raw.subarray(16300,16500));await c.api.evidenceImport({evidence_ref:e});assert.equal((await c.api.evidenceReopenVerify({evidence_ref:e})).verified,true);}));
test('strict transaction rollback',()=>withStore(async c=>{assert.throws(()=>c.store.transaction(()=>{c.store.run('INSERT INTO clients(id,bytes) VALUES(?,?)','test',Buffer.from([1]));throw Error('injected');}));assert.equal(c.store.one('SELECT * FROM clients WHERE id=?','test'),undefined);}));
test('range + offset atomic rollback via real SQLite trigger',()=>withStore(async c=>{const f=fixture(),e=await stage(c,f);c.store.db.exec("CREATE TRIGGER fail_offset BEFORE UPDATE OF offset ON downloads BEGIN SELECT RAISE(ABORT,'injected'); END;");await assert.rejects(chunks(c,e,f),/injected/);assert.equal(c.store.status(e).offset,'0');assert.equal(c.store.one('SELECT count(*) AS n FROM chunks').n,0);}));
test('partial staging hidden and resume contiguous',()=>withStore(async c=>{const f=fixture('complete',{samples:240,runtime:400000000n}),e=await stage(c,f);await c.api.evidenceCommitRange({evidence_ref:e,offset:'0',bytes_base64:f.raw.subarray(0,16384).toString('base64')});assert.equal((await c.api.evidenceListImported()).flights.length,0);await assert.rejects(c.api.evidenceImport({evidence_ref:e}),/INCOMPLETE/);c.store.reopen();assert.equal(c.store.status(e).offset,'16384');for(let o=16384;o<f.raw.length;o+=16384)await c.api.evidenceCommitRange({evidence_ref:e,offset:String(o),bytes_base64:f.raw.subarray(o,o+16384).toString('base64')});await c.api.evidenceImport({evidence_ref:e});assert.equal(c.store.list().length,1);}));
test('import row + state rollback',()=>withStore(async c=>{const f=fixture(),e=await stage(c,f);await chunks(c,e,f);c.store.db.exec("CREATE TRIGGER fail_import BEFORE UPDATE OF state ON downloads BEGIN SELECT RAISE(ABORT,'injected'); END;");await assert.rejects(c.api.evidenceImport({evidence_ref:e}),/injected/);assert.equal(c.store.list().length,0);assert.equal(c.store.status(e).state,'STAGING');}));
test('reopen verifies raw bytes; corruption denied',()=>withStore(async c=>{const e=await imported(c);assert.equal((await c.api.evidenceReopenVerify({evidence_ref:e})).verified,true);c.store.run('UPDATE chunks SET bytes=? WHERE e=?',Buffer.alloc(1088),e);await assert.rejects(c.api.evidenceReopenVerify({evidence_ref:e}),/CHUNK_HASH/);}));
test('exact E deduplication preserves imported row',()=>withStore(async c=>{const f=fixture(),e=await imported(c,f);assert.equal(await stage(c,f),e);assert.equal(c.store.list().length,1);assert.equal(c.store.status(e).state,'IMPORTED');}));
test('same S/different E preserved conflict denies local gate',()=>withStore(async c=>{const e=await imported(c);const f=fixture('incomplete');await stage(c,f);assert.equal(c.store.status(e).conflict,true);assert.equal(c.store.one('SELECT count(*) AS n FROM downloads').n,2);assert.equal((await c.api.storageQualification()).LOCAL_STORAGE_GATE_PASS,false);await assert.rejects(c.api.evidenceCreateAckPending({evidence_ref:e}),/LOCAL_GATE_DENIED/);}));
test('pending ACK survives new OS process opening database',()=>withStore(async c=>{const e=await imported(c);await c.api.evidenceCreateAckPending({evidence_ref:e});const output=execFileSync(process.execPath,['--input-type=module','-e',"import {DatabaseSync} from 'node:sqlite'; const d=new DatabaseSync(process.argv[1]); console.log(JSON.stringify(d.prepare('SELECT a.state,f.ack_status FROM ack_outbox a JOIN flights f USING(e)').get()));d.close();",c.store.path],{encoding:'utf8',windowsHide:true});const r=JSON.parse(output.trim());assert.equal(r.state,'PENDING_SYNTHETIC');assert.equal(r.ack_status,'PENDING_SYNTHETIC');}));
test('pending ACK atomic rollback',()=>withStore(async c=>{const e=await imported(c);c.store.db.exec("CREATE TRIGGER fail_ack BEFORE UPDATE OF ack_status ON flights BEGIN SELECT RAISE(ABORT,'injected'); END;");await assert.rejects(c.api.evidenceCreateAckPending({evidence_ref:e}),/injected/);assert.equal(c.store.one('SELECT * FROM ack_outbox WHERE e=?',e),undefined);assert.equal(c.store.status(e).ack_status,'LOCAL');}));
test('synthetic ACK label only and retry idempotence',()=>withStore(async c=>{const e=await imported(c);await c.api.evidenceCreateAckPending({evidence_ref:e});await c.api.evidenceMarkAcked({evidence_ref:e});assert.equal(c.store.status(e).ack_status,'ACKED_SYNTHETIC');await c.api.evidenceCreateAckPending({evidence_ref:e});assert.equal(c.store.status(e).ack_status,'ACKED_SYNTHETIC');assert.doesNotMatch(JSON.stringify(c.store.status(e)),/TRANSFERRED/);}));
test('synthetic ACK success atomic rollback',()=>withStore(async c=>{const e=await imported(c);await c.api.evidenceCreateAckPending({evidence_ref:e});c.store.db.exec("CREATE TRIGGER fail_ack BEFORE UPDATE OF ack_status ON flights BEGIN SELECT RAISE(ABORT,'injected'); END;");await assert.rejects(c.api.evidenceMarkAcked({evidence_ref:e}),/injected/);assert.equal(c.store.one('SELECT state FROM ack_outbox WHERE e=?',e).state,'PENDING_SYNTHETIC');assert.equal(c.store.status(e).ack_status,'PENDING_SYNTHETIC');}));
test('secure credential mock opaque refs only',()=>withStore(async c=>{const r=await c.api.credentialStore({fixture_id:'courier-v1'});assert.deepEqual(Object.keys(r).sort(),['credential_ref','exists','synthetic']);assert.ok(r.exists);assert.ok((await c.api.credentialExists({credential_ref:r.credential_ref})).exists);assert.equal((await c.api.credentialDelete({credential_ref:r.credential_ref})).exists,false);await assert.rejects(c.api.credentialStore({fixture_id:'real'}),/PAIRING/);}));
for(const key of ['secure','packaged','space'])test(`failed qualification ${key} denies local and full gates`,()=>withStore(async c=>{const g=await c.api.storageQualification();assert.equal(g.LOCAL_STORAGE_GATE_PASS,false);assert.equal(g.FULL_ACK_GATE_PASS,false);const e=await imported(c);await assert.rejects(c.api.evidenceCreateAckPending({evidence_ref:e}),/LOCAL_GATE_DENIED/);},{[key]:false}));
test('local gate can pass; full ACK always false',()=>withStore(async c=>{const g=await c.api.storageQualification();assert.equal(g.LOCAL_STORAGE_GATE_PASS,true);assert.equal(g.FULL_ACK_GATE_PASS,false);}));
test('serialized competing range writes yield one commit',()=>withStore(async c=>{const f=fixture(),e=await stage(c,f);const o={evidence_ref:e,offset:'0',bytes_base64:f.raw.toString('base64')};const r=await Promise.allSettled([c.api.evidenceCommitRange(o),c.api.evidenceCommitRange(o)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(c.store.status(e).offset,String(f.raw.length));}));
test('mobile qualification empty and desktop manifest separate',()=>{const q=JSON.parse(readFileSync(new URL('../mobile/qualification.json',import.meta.url),'utf8'));assert.equal(q.schema,'huginn.flight-courier.mobile-qualification');assert.deepEqual(q.qualified_builds,[]);assert.ok(q.required_fields.includes('tls_result'));const d=JSON.parse(readFileSync(new URL('../flight-compatibility.json',import.meta.url),'utf8'));assert.notEqual(q.schema,d.schema);});
test('native APIs registered on both projects; schema and transitions wired',()=>{const java=readFileSync(new URL('../android/app/src/main/java/is/huginn/foundation/dev/FlightCourierPlugin.java',import.meta.url),'utf8'),swift=readFileSync(new URL('../ios/App/App/FlightCourierPlugin.swift',import.meta.url),'utf8');for(const op of OPERATIONS){assert.ok(java.includes('void '+op+'('));assert.ok(swift.includes('func '+op+'('));}const pbx=readFileSync(new URL('../ios/App/App.xcodeproj/project.pbxproj',import.meta.url),'utf8');assert.ok(pbx.includes('CourierStore.swift in Sources'));});
test('Courier source has no networking/ACK transport API',()=>{for(const file of ['../flight-mobile.mjs','../mobile/entry.mjs','../android/app/src/main/java/is/huginn/foundation/dev/CourierStore.java','../android/app/src/main/java/is/huginn/foundation/dev/FlightCourierPlugin.java','../ios/App/App/CourierStore.swift','../ios/App/App/FlightCourierPlugin.swift']){const s=readFileSync(new URL(file,import.meta.url),'utf8');assert.doesNotMatch(s,/\bfetch\s*\(|XMLHttpRequest|WebSocket|URLSession|HttpURLConnection|OkHttp|192\.168\.4\.1|Authorization|\/api\/v1\//);}const config=JSON.parse(readFileSync(new URL('../capacitor.config.json',import.meta.url),'utf8'));assert.equal(config.server.url,undefined);assert.equal(config.plugins.CapacitorHttp.enabled,false);});

test('all eight frozen vectors run through mock native bridge and real SQLite',()=>withStore(async c=>{const asset=JSON.parse(readFileSync(new URL('./fixtures/flight-v1-vectors.json',import.meta.url),'utf8'));for(const v of asset.vectors)c.store.register(v.metadata);const result=await runLocalFixtures(c.api,asset);assert.equal(result.results.length,8);assert.ok(result.results.every(r=>r.verified));assert.equal(result.phone_qualified,false);assert.equal(result.gate.FULL_ACK_GATE_PASS,false);}));

test('bridge rejects credential response with secret material',async()=>{await assert.rejects(createCourierBridge({credentialExists:()=>({credential_ref:'opaque',exists:true,token:'forbidden'})}).credentialExists({credential_ref:'opaque'}),/CREDENTIAL_RESPONSE/);});
