package is.huginn.foundation.dev;
import android.content.Context;
import com.getcapacitor.JSObject;
import org.json.*;
import java.util.*;
import java.nio.charset.StandardCharsets;

/** Confined to the plugin serial worker. Lifecycle cancellation is thread-safe. */
final class CourierNetwork {
    final CourierStore store;final CourierCredentials secrets;final CourierHttps https;final Context context;private String validatedPeer="";java.util.function.Consumer<JSObject> progress=status->{};
    CourierNetwork(Context c,CourierStore store){this.context=c;this.store=store;secrets=new CourierCredentials(c);https=new CourierHttps(c);}
    // Native-only scanner/manual/unit entry; NOT a Capacitor operation.
    JSObject intake(byte[] raw)throws Exception {validatedPeer="";JSONObject o;try{o=CourierContract.pairing(raw);}finally{Arrays.fill(raw,(byte)0);}String device=CourierContract.string(o,"source_device_id"),pin=CourierContract.string(o,"tls_spki_sha256");String ref=store.query("SELECT ref FROM courier_pairs WHERE device=?",device);if(ref==null)ref="paired-"+UUID.randomUUID().toString().replace("-","");String credential="paired-"+UUID.randomUUID().toString().replace("-","");secrets.storeNative(credential,CourierContract.string(o,"token").getBytes(StandardCharsets.US_ASCII));final String r=ref;try{store.transaction(()->{store.write("INSERT OR REPLACE INTO courier_pairs(ref,device,pin,credential,repair) VALUES(?,?,?,?,0)",r,device,pin,credential);return null;});}catch(Exception error){secrets.delete(credential);throw error;}JSObject out=new JSObject();out.put("paired_ref",ref);out.put("source_device_id",device);out.put("state","PAIRED");return out;}
    String device(String ref)throws Exception {CourierContract.need(ref.matches("paired-[0-9a-f]{32}"),"PAIRED_REF");String d=store.query("SELECT device FROM courier_pairs WHERE ref=?",ref);CourierContract.need(d!=null,"PAIRING_REQUIRED");return d;}
    CourierHttps.Response request(String ref,String path,byte[] post,String range,String etag,int cap)throws Exception {
        device(ref);CourierContract.need(store.number("SELECT repair FROM courier_pairs WHERE ref=?",ref)==0,"REPAIR_REQUIRED");byte[] token=secrets.readNative(store.query("SELECT credential FROM courier_pairs WHERE ref=?",ref));CourierContract.need(token!=null&&token.length==43,"CREDENTIAL_UNAVAILABLE");
        int epoch=https.epoch();try {for(int attempt=0;attempt<3;attempt++){https.check(epoch);CourierHttps.Response r=https.request(path,store.query("SELECT pin FROM courier_pairs WHERE ref=?",ref),token,post,range,etag,cap);if(r.status<400)return r;JSONObject error=CourierContract.json(r.body,512);CourierContract.keys(error,"error");String code=CourierContract.remoteError(CourierContract.string(error,"error"));if((r.status==401&&Arrays.asList("AUTH_REQUIRED","INVALID_TOKEN").contains(code))||(r.status==403&&code.equals("TOKEN_REVOKED"))){store.transaction(()->{store.write("UPDATE courier_pairs SET repair=1 WHERE ref=?",ref);return null;});throw new IllegalArgumentException("REPAIR_REQUIRED");}if(r.status==503&&"1".equals(r.header("retry-after"))&&attempt<2){for(int i=0;i<10;i++){https.check(epoch);Thread.sleep(100);}continue;}throw new IllegalArgumentException(r.status==503?"RETRYABLE_503":code);}throw new IllegalArgumentException("RETRY_BUDGET");}finally{Arrays.fill(token,(byte)0);}
    }
    JSONObject detail(String ref,String session)throws Exception {CourierContract.hex(session,32,"SESSION");CourierHttps.Response r=request(ref,"/api/v1/flights/"+session,null,null,null,2048);CourierContract.need(r.status==200,"DETAIL_STATUS");JSONObject m=CourierContract.metadata(CourierContract.json(r.body,2048),device(ref),true);CourierContract.need(CourierContract.string(m,"session_id").equals(session)&&CourierContract.etag(m).equals(r.header("etag")),"DETAIL_IDENTITY");CourierContract.identity(m);validatedPeer=ref+"|"+store.query("SELECT pin FROM courier_pairs WHERE ref=?",ref);return m;}
    JSObject dispatch(String op,JSONObject options,boolean packaged)throws Exception {
        CourierContract.keys(options,op.equals("courierCancel")?"":op.equals("courierDetail")||op.equals("courierDownload")?"paired_ref session_id":"paired_ref");
        if(op.equals("courierCancel")){https.cancel();return state("CANCELLED");}String ref=CourierContract.string(options,"paired_ref"),d=device(ref);
        if(op.equals("courierConnection")){JSObject out=state(store.number("SELECT repair FROM courier_pairs WHERE ref=?",ref)==1?"REPAIR_REQUIRED":"PAIRED");out.put("source_device_id",d);out.put("FULL_ACK_GATE_PASS",fullGate(ref,packaged));out.put("trust_profile",CourierHttps.PROFILE);return out;}
        if(op.equals("courierList"))return enumerate(ref,d);
        if(op.equals("courierDetail"))return JSObject.fromJSONObject(detail(ref,CourierContract.string(options,"session_id")));
        if(op.equals("courierDownload"))return download(ref,CourierContract.string(options,"session_id"),packaged);
        if(op.equals("courierRetryAcks"))return retry(ref,packaged);
        throw new IllegalArgumentException("UNKNOWN_OPERATION");
    }
    static JSObject state(String s){JSObject o=new JSObject();o.put("state",s);return o;}
    JSObject enumerate(String ref,String d)throws Exception {int epoch=https.epoch();for(int restart=0;restart<3;restart++){JSONArray entries=new JSONArray();Set<String> cursors=new HashSet<>(),sessions=new HashSet<>();String cursor=null;long generation=-1,count=-1;try{for(int page=0;page<8;page++){https.check(epoch);String path="/api/v1/flights?limit=8"+(cursor==null?"":"&cursor="+cursor);CourierHttps.Response r=request(ref,path,null,null,null,16384);CourierContract.need(r.status==200,"LIST_STATUS");JSONObject list=CourierContract.list(r.body,d,8);long g=CourierContract.uint(list,"manifest_generation",0xffffffffL),c=CourierContract.uint(list,"count",64);if(generation<0){generation=g;count=c;}CourierContract.need(generation==g&&count==c,"LIST_SNAPSHOT_CHANGED");JSONArray rows=list.getJSONArray("entries");for(int i=0;i<rows.length();i++){JSONObject m=rows.getJSONObject(i);String id=m.isNull("session_id")?"filename:"+m.getString("filename"):m.getString("session_id");CourierContract.need(sessions.add(id),"DUPLICATE_SESSION");entries.put(m);}if(list.isNull("next_cursor")){CourierContract.need(entries.length()==count,"LIST_COUNT");JSObject out=new JSObject();out.put("entries",entries);out.put("manifest_generation",generation);out.put("source_device_id",d);validatedPeer=ref+"|"+store.query("SELECT pin FROM courier_pairs WHERE ref=?",ref);return out;}cursor=CourierContract.string(list,"next_cursor");CourierContract.need(cursors.add(cursor)&&rows.length()==8,"CURSOR_LOOP");}throw new IllegalArgumentException("PAGE_BUDGET");}catch(IllegalArgumentException e){if(!"CURSOR_STALE".equals(e.getMessage())||restart==2)throw e;}}throw new IllegalArgumentException("CURSOR_RETRY_BUDGET");}
    JSObject download(String ref,String session,boolean packaged)throws Exception {int epoch=https.epoch();CourierContract.hex(session,32,"SESSION");String existing=store.query("SELECT e FROM downloads WHERE s=? LIMIT 1",device(ref)+"|"+session);if(existing!=null){store.reopen();store.revalidateCommitted(existing);CourierContract.need(!"SOURCE_CHANGED".equals(store.query("SELECT state FROM downloads WHERE e=?",existing)),"SOURCE_CHANGED");}JSONObject m=detail(ref,session);String d=device(ref),sha=m.getString("metadata_sha256"),e=d+"|"+session+"|"+sha,s=d+"|"+session;byte[] identity=CourierContract.identity(m);long size=EvidenceVerifier.physical(identity);
        String prior=store.query("SELECT e FROM downloads WHERE s=? AND e!=? LIMIT 1",s,e);if(prior!=null){conflict(prior);throw new IllegalArgumentException("SOURCE_CHANGED");}
        CourierContract.need(CourierContract.automatic(m),"OWNER_SELECTION_REQUIRED");String saved=store.query("SELECT detail FROM courier_remote WHERE e=?",e);if(saved!=null){JSONObject old=CourierContract.json(saved.getBytes(StandardCharsets.UTF_8),2048);for(String k:Arrays.asList("session_id","physical_sha256","physical_bytes","metadata_sha256"))if(!old.get(k).equals(m.get(k))){conflict(e);throw new IllegalArgumentException("SOURCE_CHANGED");}store.reopen();store.revalidateCommitted(e);}else{store.transaction(()->{store.write("INSERT OR IGNORE INTO downloads(e,s,metadata) VALUES(?,?,?)",e,s,identity);CourierContract.need(Arrays.equals(store.metadata(e),identity),"DUPLICATE_METADATA");store.write("INSERT INTO courier_remote(e,detail) VALUES(?,?)",e,m.toString());return null;});}
        CourierContract.need(store.number("SELECT count(*) FROM downloads WHERE s=?",s)==1&&!"SOURCE_CHANGED".equals(store.query("SELECT state FROM downloads WHERE e=?",e)),"SOURCE_CHANGED");
        while(store.number("SELECT offset FROM downloads WHERE e=?",e)<size){https.check(epoch);long start=store.number("SELECT offset FROM downloads WHERE e=?",e),end=Math.min(start+16384,size)-1;CourierHttps.Response r;try{r=request(ref,"/api/v1/flights/"+session+"/evidence",null,"bytes="+start+"-"+end,CourierContract.etag(m),16384);}catch(IllegalArgumentException ex){if("EVIDENCE_CHANGED".equals(ex.getMessage())){conflict(e);try{detail(ref,session);}catch(Exception ignored){}throw new IllegalArgumentException("SOURCE_CHANGED");}throw ex;}CourierContract.need(r.status==206&&Long.toString(end-start+1).equals(r.header("content-length"))&&("bytes "+start+"-"+end+"/"+size).equals(r.header("content-range"))&&CourierContract.etag(m).equals(r.header("etag"))&&"bytes".equals(r.header("accept-ranges"))&&r.body.length==end-start+1,"RANGE_RESPONSE");https.check(epoch);store.commitNative(e,start,r.body);progress.accept(store.status(e));Arrays.fill(r.body,(byte)0);}
        store.reopen();store.verify(e);https.check(epoch);store.transaction(()->{store.write("INSERT OR IGNORE INTO flights(e,s) SELECT e,s FROM downloads WHERE e=?",e);store.write("UPDATE downloads SET state='IMPORTED' WHERE e=?",e);return null;});store.reopen();store.verify(e);CourierContract.need(store.qualification(packaged).getBoolean("LOCAL_STORAGE_GATE_PASS"),"LOCAL_GATE_DENIED");JSONObject ack=CourierContract.ack(d,store.metadata(e),sha);store.transaction(()->{store.write("INSERT OR IGNORE INTO courier_ack(e,device,request,state) VALUES(?,?,?,'PENDING')",e,d,ack.toString());store.write("UPDATE flights SET ack_status=(SELECT state FROM courier_ack WHERE e=?) WHERE e=?",e,e);return null;});return store.status(e);
    }
    void conflict(String e)throws Exception {store.transaction(()->{store.write("UPDATE downloads SET state='SOURCE_CHANGED' WHERE e=?",e);return null;});}
    boolean fullGate(String ref,boolean packaged)throws Exception {return store.number("SELECT repair FROM courier_pairs WHERE ref=?",ref)==0&&secrets.exists(store.query("SELECT credential FROM courier_pairs WHERE ref=?",ref))&&CourierQualification.full(context,store,packaged,validatedPeer.equals(ref+"|"+store.query("SELECT pin FROM courier_pairs WHERE ref=?",ref)));}
    JSObject retry(String ref,boolean packaged)throws Exception {int epoch=https.epoch();https.check(epoch);device(ref);CourierContract.need(fullGate(ref,packaged),"MOBILE_QUALIFICATION_REQUIRED");
        CourierContract.need(store.qualification(packaged).getBoolean("LOCAL_STORAGE_GATE_PASS"),"LOCAL_GATE_DENIED");for(String e:store.pending(device(ref))){https.check(epoch);store.reopen();store.verify(e);byte[] persistedRequest=store.query("SELECT request FROM courier_ack WHERE e=?",e).getBytes(StandardCharsets.UTF_8);JSONObject ack=CourierContract.json(persistedRequest,1024);JSONObject expected=CourierContract.ack(device(ref),store.metadata(e),e.substring(e.lastIndexOf('|')+1));for(String k:Arrays.asList("schema","schema_version","session_id","physical_sha256","physical_bytes","metadata_sha256"))CourierContract.need(expected.get(k).equals(ack.get(k)),"OUTBOX_IDENTITY");
            store.transaction(()->{store.write("UPDATE courier_ack SET state='OUTCOME_UNKNOWN' WHERE e=?",e);return null;});CourierHttps.Response r=request(ref,"/api/v1/flights/"+ack.getString("session_id")+"/ack",persistedRequest,null,null,1024);CourierContract.need(r.status==200,"ACK_STATUS");CourierContract.ackResult(r.body,ack);store.transaction(()->{store.write("UPDATE courier_ack SET state='ACKED' WHERE e=?",e);store.write("UPDATE flights SET ack_status='ACKED' WHERE e=?",e);return null;});}return state("ACK_RETRY_COMPLETE");
    }
}
