package is.huginn.foundation.dev;

import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

@CapacitorPlugin(name="FlightCourier")
public final class FlightCourierPlugin extends Plugin {
    private final ExecutorService worker=Executors.newSingleThreadExecutor();private CourierStore store;private volatile CourierNetwork network;private volatile boolean foreground=true;private final Object progressLock=new Object();private com.getcapacitor.JSObject latestProgress;private boolean progressQueued;
    private void invoke(String operation,PluginCall call){worker.execute(()->{try{if(store==null)store=new CourierStore(getContext());if(network==null){network=new CourierNetwork(getContext(),store);network.progress=this::progress;network.https.foreground(foreground);}boolean packaged=getBridge().getConfig().getServerUrl()==null;if(operation.equals("courierPairs")){CourierContract.keys(call.getData(),"");org.json.JSONArray pairs=new org.json.JSONArray();try(android.database.Cursor cursor=store.uiRows("SELECT ref,device,pin,repair FROM courier_pairs ORDER BY device LIMIT 64",null)){while(cursor.moveToNext()){com.getcapacitor.JSObject p=new com.getcapacitor.JSObject();p.put("paired_ref",cursor.getString(0));p.put("source_device_id",cursor.getString(1));p.put("fingerprint",cursor.getString(2).substring(0,12));p.put("trust_profile","DEVELOPMENT");p.put("state",cursor.getInt(3)==1?"REPAIR_REQUIRED":"PAIRED_OFFLINE");pairs.put(p);}}com.getcapacitor.JSObject r=new com.getcapacitor.JSObject();r.put("pairs",pairs);call.resolve(r);return;}if(operation.equals("courierLocalList")){CourierContract.keys(call.getData(),"after");String after=call.getString("after","");CourierContract.need(after.length()<=256,"FIELD_LIMIT");org.json.JSONArray rows=new org.json.JSONArray();try(android.database.Cursor cursor=store.uiRows("SELECT d.e,r.detail FROM downloads d JOIN courier_remote r ON d.e=r.e WHERE d.e>? ORDER BY d.e LIMIT 16",new String[]{after})){while(cursor.moveToNext()){com.getcapacitor.JSObject row=store.status(cursor.getString(0));row.put("metadata",CourierContract.json(cursor.getString(1).getBytes(java.nio.charset.StandardCharsets.UTF_8),2048));rows.put(row);}}com.getcapacitor.JSObject r=new com.getcapacitor.JSObject();r.put("evidence",rows);call.resolve(r);return;}if(operation.equals("courierPairManual")){CourierContract.keys(call.getData(),"");CourierContract.need(packaged,"PACKAGED_CONTEXT_REQUIRED");getActivity().runOnUiThread(()->pairDialog(call));return;}if(operation.equals("courierOwnerTransfer")){CourierContract.keys(call.getData(),"paired_ref session_id");CourierContract.need(packaged,"PACKAGED_CONTEXT_REQUIRED");String ref=call.getString("paired_ref"),id=call.getString("session_id");org.json.JSONObject m=network.detail(ref,id);CourierContract.need(CourierNetwork.ownerSelectable(m),"OWNER_SELECTION_REQUIRED");getActivity().runOnUiThread(()->ownerDialog(call,ref,id,m,packaged));return;}call.resolve(operation.startsWith("courier")?network.dispatch(operation,call.getData(),packaged):store.dispatch(operation,call.getData(),packaged,BuildConfig.DEBUG));}catch(Exception e){call.reject(CourierErrors.publicCode(e));}});}
    @PluginMethod public void platformInfo(PluginCall c){invoke("platformInfo",c);}
    @PluginMethod public void storageQualification(PluginCall c){invoke("storageQualification",c);}
    @PluginMethod public void evidenceCreateStaging(PluginCall c){invoke("evidenceCreateStaging",c);}
    @PluginMethod public void evidenceCommitRange(PluginCall c){invoke("evidenceCommitRange",c);}
    @PluginMethod public void evidenceListImported(PluginCall c){invoke("evidenceListImported",c);}
    @PluginMethod public void evidenceGetStatus(PluginCall c){invoke("evidenceGetStatus",c);}
    @PluginMethod public void evidenceReadRange(PluginCall c){invoke("evidenceReadRange",c);}
    @PluginMethod public void evidenceImport(PluginCall c){invoke("evidenceImport",c);}
    @PluginMethod public void evidenceReopenVerify(PluginCall c){invoke("evidenceReopenVerify",c);}
    @PluginMethod public void evidenceCreateAckPending(PluginCall c){invoke("evidenceCreateAckPending",c);}
    @PluginMethod public void evidenceMarkAcked(PluginCall c){invoke("evidenceMarkAcked",c);}
    @PluginMethod public void credentialStore(PluginCall c){invoke("credentialStore",c);}
    @PluginMethod public void credentialExists(PluginCall c){invoke("credentialExists",c);}
    @PluginMethod public void credentialDelete(PluginCall c){invoke("credentialDelete",c);}

    @PluginMethod public void courierPairs(PluginCall c){invoke("courierPairs",c);}
    @PluginMethod public void courierLocalList(PluginCall c){invoke("courierLocalList",c);}
    @PluginMethod public void courierPairManual(PluginCall c){invoke("courierPairManual",c);}
    @PluginMethod public void courierOwnerTransfer(PluginCall c){invoke("courierOwnerTransfer",c);}
    private void pairDialog(PluginCall call){android.widget.EditText input=new android.widget.EditText(getContext());input.setHint("Paste pairing data from HuginnEIS");input.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE|android.text.InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);input.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(4096)});input.setTransformationMethod(android.text.method.PasswordTransformationMethod.getInstance());input.setImportantForAutofill(android.view.View.IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS);android.app.AlertDialog dialog=new android.app.AlertDialog.Builder(getActivity()).setTitle("Pair / re-pair HuginnEIS").setMessage("Pairing changes the credential association. Stored evidence and pending acknowledgements are retained.").setView(input).setNegativeButton("Cancel",(d,w)->{input.setText("");call.reject("CANCELLED");}).setPositiveButton("Pair",null).create();dialog.setOnCancelListener(d->{input.setText("");call.reject("CANCELLED");});dialog.setOnShowListener(d->{dialog.getWindow().addFlags(android.view.WindowManager.LayoutParams.FLAG_SECURE);dialog.getButton(android.app.AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{byte[] raw=input.getText().toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);input.setText("");dialog.dismiss();worker.execute(()->{try{CourierContract.need(foreground,"FOREGROUND_REQUIRED");call.resolve(network.intake(raw));}catch(Exception e){call.reject(CourierErrors.publicCode(e));}finally{java.util.Arrays.fill(raw,(byte)0);}});});});dialog.show();}
    private void ownerDialog(PluginCall call,String ref,String id,org.json.JSONObject m,boolean packaged){try{boolean corrupt=m.getString("state").equals("CORRUPT");String sha=m.getString("metadata_sha256");new android.app.AlertDialog.Builder(getActivity()).setTitle(corrupt?"Corrupt evidence":"Provisional evidence").setMessage(corrupt?"This file contains corrupt evidence. The original bytes will be preserved for forensic review.":"This recording did not qualify as a Flight. Transfer provisional evidence anyway?").setNegativeButton("Cancel",(d,w)->call.reject("CANCELLED")).setOnCancelListener(d->call.reject("CANCELLED")).setPositiveButton(corrupt?"Transfer forensic evidence":"Transfer evidence",(d,w)->worker.execute(()->{try{CourierContract.need(foreground,"FOREGROUND_REQUIRED");call.resolve(network.download(ref,id,packaged,sha));}catch(Exception e){call.reject(CourierErrors.publicCode(e));}})).show();}catch(Exception e){call.reject("OWNER_SELECTION_REQUIRED");}}
    private void progress(com.getcapacitor.JSObject status){synchronized(progressLock){latestProgress=status;if(progressQueued)return;progressQueued=true;}getActivity().runOnUiThread(()->{com.getcapacitor.JSObject latest;synchronized(progressLock){latest=latestProgress;latestProgress=null;progressQueued=false;}notifyListeners("courierProgress",latest);});}
    @Override protected void handleOnPause(){foreground=false;if(network!=null)network.https.foreground(false);}
    @Override protected void handleOnResume(){foreground=true;if(network!=null)network.https.foreground(true);}
    @Override protected void handleOnDestroy(){foreground=false;if(network!=null)network.https.foreground(false);worker.shutdown();}
    @PluginMethod public void courierConnection(PluginCall c){invoke("courierConnection",c);}
    @PluginMethod public void courierList(PluginCall c){invoke("courierList",c);}
    @PluginMethod public void courierDetail(PluginCall c){invoke("courierDetail",c);}
    @PluginMethod public void courierDownload(PluginCall c){invoke("courierDownload",c);}
    @PluginMethod public void courierRetryAcks(PluginCall c){invoke("courierRetryAcks",c);}
    @PluginMethod public void courierCancel(PluginCall c){if(c.getData().length()!=0){c.reject("JSON_KEYS");return;}if(network!=null)network.https.cancel();com.getcapacitor.JSObject r=new com.getcapacitor.JSObject();r.put("state","CANCELLED");c.resolve(r);}
}
