import Foundation
import CoreFoundation

// Duplicate decoded keys are checked before JSONSerialization; all firmware
// JSON numbers are integral. Decimal strings retain their full 64-bit range.
enum CourierWire {
    // Frozen 3F public codes only; arbitrary server text never crosses bridge.
    static func remoteError(_ code:String)->String { ["ACK_DEFERRED","ACTIVE_FLIGHT","AMBIGUOUS_SESSION","AUTH_REQUIRED","AUTOMATIC","BODY_TOO_LARGE","COMMIT_UNCERTAIN","COMPLETE","CORRUPT","COURIER_BUSY","CURSOR_STALE","EVIDENCE_CHANGED","EVIDENCE_MISMATCH","HFC","HFCM","IF_MATCH_REQUIRED","INCOMPLETE","INVALID_ACK","INVALID_BODY","INVALID_CURSOR","INVALID_IF_MATCH","INVALID_JSON","INVALID_QUERY","INVALID_RANGE","INVALID_REQUEST","INVALID_SESSION_ID","INVALID_TOKEN","IO_FAILED","MEMORY_UNAVAILABLE","METADATA_CHANGED","METHOD_NOT_ALLOWED","NOT_FOUND","NOT_TRANSFERRED","OK","ORIGIN_DENIED","OWNER_SELECTION_REQUIRED_FORENSIC","OWNER_SELECTION_REQUIRED_PROVISIONAL","PROVISIONAL","QUALIFIED_OPEN","RANGE_NOT_SATISFIABLE","RANGE_REQUIRED","RANGE_TOO_LARGE","RECOVERY_PENDING","SD_UNAVAILABLE","SESSION_NOT_FOUND","SOURCE_ID_UNAVAILABLE","SOURCE_UNAVAILABLE","TOKEN_REVOKED","TRANSFERRED","UNSUPPORTED_HFL_VERSION","UNTRUSTED_SESSION"].contains(code) ? code:"REMOTE_ERROR" }
    static let states=["","PROVISIONAL","QUALIFIED_OPEN","COMPLETE","INCOMPLETE","CORRUPT"]
    static let reasons=["AMBIGUOUS_SESSION","UNTRUSTED_SESSION","UNSUPPORTED_HFL_VERSION","SOURCE_UNAVAILABLE","ACTIVE_FLIGHT","OWNER_SELECTION_REQUIRED_FORENSIC","OWNER_SELECTION_REQUIRED_PROVISIONAL","AUTOMATIC"]
    static func match(_ s:String,_ pattern:String)->Bool { s.range(of:"^(?:"+pattern+")$",options:.regularExpression) != nil }
    static func string(_ o:[String:Any],_ k:String)throws->String { guard let v=o[k] as? String else { throw CourierError("JSON_STRING") };return v }
    static func bool(_ o:[String:Any],_ k:String)throws->Bool { guard let n=o[k] as? NSNumber,CFGetTypeID(n)==CFBooleanGetTypeID() else { throw CourierError("JSON_BOOLEAN") };return n.boolValue }
    static func uint(_ o:[String:Any],_ k:String,_ max:UInt64)throws->UInt64 { guard let n=o[k] as? NSNumber,CFGetTypeID(n) != CFBooleanGetTypeID(),let v=UInt64(n.stringValue),v<=max else { throw CourierError("JSON_INTEGER") };return v }
    static func decimal(_ o:[String:Any],_ k:String)throws->UInt64 { let s=try string(o,k);try require(match(s,"0|[1-9][0-9]*"),"DECIMAL");guard let n=UInt64(s) else { throw CourierError("DECIMAL_RANGE") };return n }
    static func signed(_ o:[String:Any],_ k:String)throws->Int64 { let s=try string(o,k);try require(match(s,"0|-?[1-9][0-9]*"),"DECIMAL");guard let n=Int64(s) else { throw CourierError("DECIMAL_RANGE") };return n }
    static func keys(_ o:[String:Any],_ names:String)throws { try require(Set(o.keys)==Set(names.split(separator:" ").map(String.init)),"JSON_KEYS") }
    static func base(_ o:[String:Any],_ schema:String,_ device:String?=nil)throws { try require(try string(o,"schema")==schema && uint(o,"schema_version",1)==1,"SCHEMA");if let d=device { try require(try string(o,"source_device_id")==d,"SOURCE_DEVICE_MISMATCH") } }
    final class Scanner {
        let b:[UInt8];var at=0
        init(_ data:Data)throws { try require(String(data:data,encoding:.utf8) != nil,"JSON_UTF8");b=Array(data) }
        func ws(){ while at<b.count && [9,10,13,32].contains(b[at]) { at+=1 } }
        func take(_ c:UInt8)throws { ws();try require(at<b.count && b[at]==c,"JSON_SYNTAX");at+=1 }
        func text()throws->String { ws();let start=at;try take(34);while at<b.count { let c=b[at];at+=1;if c==34 { let raw=Data(b[start..<at]);guard let s=try JSONSerialization.jsonObject(with:raw,options:.fragmentsAllowed) as? String else { throw CourierError("JSON_STRING") };return s };try require(c>=32,"JSON_STRING");if c==92 { try require(at<b.count,"JSON_ESCAPE");at+=1 } };throw CourierError("JSON_STRING") }
        func value(_ depth:Int)throws { try require(depth<=8,"JSON_DEPTH");ws();try require(at<b.count,"JSON_SYNTAX");let c=b[at]
            if c==123 { at+=1;ws();if at<b.count && b[at]==125 { at+=1;return };var keys=Set<String>();while true { try require(keys.insert(try text()).inserted,"JSON_DUPLICATE");try take(58);try value(depth+1);ws();try require(at<b.count,"JSON_SYNTAX");if b[at]==125 { at+=1;return };try take(44) } }
            else if c==91 { at+=1;ws();if at<b.count && b[at]==93 { at+=1;return };var count=0;while true { count+=1;try require(count<=64,"JSON_ARRAY_LIMIT");try value(depth+1);ws();try require(at<b.count,"JSON_SYNTAX");if b[at]==93 { at+=1;return };try take(44) } }
            else if c==34 { _=try text() }
            else { let start=at;while at<b.count && ![44,93,125,9,10,13,32].contains(b[at]) { at+=1 };let s=String(bytes:b[start..<at],encoding:.utf8) ?? "";try require(["null","true","false"].contains(s)||match(s,"-?(0|[1-9][0-9]*)"),"JSON_SCALAR") }
        }
        func check()throws { ws();try require(at<b.count && b[at]==123,"JSON_OBJECT");try value(0);ws();try require(at==b.count,"JSON_TRAILING") }
    }
    static func json(_ b:Data,_ max:Int)throws->[String:Any] { try require(b.count<=max,"RESPONSE_LIMIT");try Scanner(b).check();guard let o=try JSONSerialization.jsonObject(with:b) as? [String:Any] else { throw CourierError("JSON_OBJECT") };return o }
    static func pairing(_ b:Data)throws->[String:Any] { let o=try json(b,512);try keys(o,"schema schema_version source_device_id tls_spki_sha256 token");try base(o,"huginn.flight-courier.pair");try require(try match(string(o,"source_device_id"),"[0-9A-F]{2}(:[0-9A-F]{2}){5}") && match(string(o,"tls_spki_sha256"),"[0-9a-f]{64}"),"PAIR_IDENTITY");let token=try string(o,"token");try require(match(token,"[A-Za-z0-9_-]{43}"),"PAIR_TOKEN");let padded=token.replacingOccurrences(of:"-",with:"+").replacingOccurrences(of:"_",with:"/")+"=";guard let decoded=Data(base64Encoded:padded),decoded.count==32 else { throw CourierError("PAIR_TOKEN") };try require(decoded.base64EncodedString().replacingOccurrences(of:"+",with:"-").replacingOccurrences(of:"/",with:"_").replacingOccurrences(of:"=",with:"")==token,"PAIR_TOKEN");return o }
    static func metadata(_ o:[String:Any],_ d:String,_ detail:Bool)throws->[String:Any] {
        try keys(o,"schema schema_version source_device_id manifest_generation session_id filename start_utc state complete integrity record_count valid_bytes runtime_us transfer_state physical_bytes hfl_version eligible reason physical_sha256 metadata_sha256");try base(o,"huginn.flight-courier.metadata",d);_=try uint(o,"manifest_generation",0xffffffff)
        if o["session_id"] is NSNull { try require(!detail,"UNTRUSTED_SESSION") } else { try require(try match(string(o,"session_id"),"[0-9a-f]{32}"),"SESSION") }
        try require(try match(string(o,"filename"),"[PF][0-9A-F]{6}\\.FLG"),"FILENAME");_=try signed(o,"start_utc");_=try decimal(o,"runtime_us");let state=try string(o,"state");try require(states.dropFirst().contains(state),"STATE");try require(try bool(o,"complete")==state.elementsEqual("COMPLETE"),"COMPLETE");try require(try uint(o,"integrity",3)>=1,"INTEGRITY");let count=try uint(o,"record_count",0xffffffff),valid=try uint(o,"valid_bytes",0xffffffff);try require(valid==128+160*count,"VALID_BYTES")
        if o["physical_bytes"] is NSNull { try require(!detail,"PHYSICAL_BYTES") } else { try require(try decimal(o,"physical_bytes")>=valid,"PHYSICAL_BYTES") }
        if o["hfl_version"] is NSNull { try require(!detail,"HFL_VERSION") } else { try require(try uint(o,"hfl_version",2)>=1,"HFL_VERSION") }
        try require(try ["TRANSFERRED","NOT_TRANSFERRED"].contains(string(o,"transfer_state")),"TRANSFER_STATE");let reason=try string(o,"reason");try require(reasons.contains(reason),"REASON");try require(try bool(o,"eligible")==["AUTOMATIC","OWNER_SELECTION_REQUIRED_FORENSIC","OWNER_SELECTION_REQUIRED_PROVISIONAL"].contains(reason),"ELIGIBILITY")
        for h in ["physical_sha256","metadata_sha256"] { if detail { try require(try match(string(o,h),"[0-9a-f]{64}"),"HASH") } else { try require(o[h] is NSNull,"LIST_HASH") } };return o
    }
    static func list(_ b:Data,_ d:String)throws->[String:Any] { let o=try json(b,16384);try keys(o,"schema schema_version source_device_id manifest_generation count capacity entries next_cursor");try base(o,"huginn.flight-courier.list",d);let g=try uint(o,"manifest_generation",0xffffffff),count=try uint(o,"count",64);try require(try uint(o,"capacity",64)==64,"CAPACITY");guard let a=o["entries"] as? [[String:Any]] else { throw CourierError("ENTRIES") };try require(a.count<=8 && UInt64(a.count)<=count,"PAGE_COUNT");for m in a { _=try metadata(m,d,false);try require(try uint(m,"manifest_generation",0xffffffff)==g,"GENERATION") };if !(o["next_cursor"] is NSNull) { try require(try match(string(o,"next_cursor"),"[A-Za-z0-9_-]{38}"),"CURSOR") };return o }
    static func automatic(_ m:[String:Any])throws->Bool { try bool(m,"eligible") && string(m,"reason")=="AUTOMATIC" && ["COMPLETE","INCOMPLETE"].contains(string(m,"state")) }
    static func unhex(_ s:String)throws->Data { try require(match(s,"(?:[0-9a-f]{2})*"),"HEX");let a=Array(s.utf8);var b=Data();for i in stride(from:0,to:a.count,by:2){ b.append(UInt8(String(bytes:a[i..<i+2],encoding:.utf8)!,radix:16)!) };return b }
    static func identity(_ o:[String:Any])throws->Data { var b=Data(repeating:0,count:108);func le(_ at:Int,_ n:Int,_ value:UInt64){ for i in 0..<n { b[at+i]=UInt8(truncatingIfNeeded:value>>(i*8)) } };b.replaceSubrange(0..<4,with:Data("HFCM".utf8));le(4,2,1);le(6,2,11);b.replaceSubrange(8..<24,with:try unhex(string(o,"session_id")));b.replaceSubrange(24..<56,with:try unhex(string(o,"physical_sha256")));le(56,8,try decimal(o,"physical_bytes"));le(64,8,UInt64(bitPattern:try signed(o,"start_utc")));le(72,8,try decimal(o,"runtime_us"));le(80,4,try uint(o,"record_count",0xffffffff));le(84,4,try uint(o,"valid_bytes",0xffffffff));b[88]=UInt8(states.firstIndex(of:try string(o,"state"))!);b[89]=UInt8(try uint(o,"integrity",3));b[90]=try bool(o,"complete") ? 1:0;b[91]=UInt8(try uint(o,"hfl_version",2));b.replaceSubrange(92..<103,with:Data(try string(o,"filename").utf8));try EvidenceVerifier.metadata(b,string(o,"metadata_sha256"));return b }
    static func etag(_ m:[String:Any])throws->String { try "\"hfl-sha256-"+string(m,"physical_sha256")+"-"+string(m,"physical_bytes")+"\"" }
    static func ack(_ m:Data,_ sha:String)throws->[String:Any] { ["schema":"huginn.flight-courier.ack","schema_version":1,"session_id":m.part(8,16).hex,"physical_sha256":m.part(24,32).hex,"physical_bytes":String(try EvidenceVerifier.physical(m)),"metadata_sha256":sha] }
    static func ackResult(_ b:Data,_ sent:[String:Any])throws { let o=try json(b,1024);try keys(o,"schema schema_version session_id physical_sha256 physical_bytes metadata_sha256 transfer_state manifest_generation already_transferred");try base(o,"huginn.flight-courier.ack-result");for k in ["session_id","physical_sha256","physical_bytes","metadata_sha256"] { try require(try string(o,k)==string(sent,k),"ACK_IDENTITY") };try require(try string(o,"transfer_state")=="TRANSFERRED","ACK_STATE");_=try uint(o,"manifest_generation",0xffffffff);_=try bool(o,"already_transferred") }
}
