import Foundation

// Native-only transport/durability authority. Confined to SQLite's serial worker.
final class CourierNetwork {
    let store:CourierStore;let secrets=CourierCredentials();let https=CourierHTTPS();private var validatedPeer="";var progress:(([String:Any])->Void)?
    init(_ store:CourierStore){ self.store=store }
    // Native scanner/manual/unit entry only; no Capacitor method accepts QR/token.
    func intake(_ raw:inout Data)throws->[String:Any] { validatedPeer="";defer { raw.resetBytes(in:0..<raw.count) };let o=try CourierWire.pairing(raw),device=try CourierWire.string(o,"source_device_id"),pin=try CourierWire.string(o,"tls_spki_sha256");let old=try store.text("SELECT ref FROM courier_pairs WHERE device=?",[device]);let ref=old.isEmpty ? "paired-"+UUID().uuidString.replacingOccurrences(of:"-",with:"").lowercased():old;let credential="paired-"+UUID().uuidString.replacingOccurrences(of:"-",with:"").lowercased();try secrets.storeNative(credential,Data(try CourierWire.string(o,"token").utf8));do { try store.transaction { try store.run("INSERT OR REPLACE INTO courier_pairs(ref,device,pin,credential,repair) VALUES(?,?,?,?,0)",[ref,device,pin,credential]) } } catch { try? secrets.delete(credential);throw error };return ["paired_ref":ref,"source_device_id":device,"state":"PAIRED"] }
    func ownerSelectable(_ m:[String:Any])throws->Bool { try CourierWire.bool(m,"eligible") && ((CourierWire.string(m,"state")=="PROVISIONAL" && CourierWire.string(m,"reason")=="OWNER_SELECTION_REQUIRED_PROVISIONAL") || (CourierWire.string(m,"state")=="CORRUPT" && CourierWire.uint(m,"integrity",3)==3 && CourierWire.string(m,"reason")=="OWNER_SELECTION_REQUIRED_FORENSIC")) }
    func device(_ ref:String)throws->String { try require(CourierWire.match(ref,"paired-[0-9a-f]{32}"),"PAIRED_REF");let d=try store.text("SELECT device FROM courier_pairs WHERE ref=?",[ref]);try require(!d.isEmpty,"PAIRING_REQUIRED");return d }
    func request(_ ref:String,_ path:String,_ post:Data?=nil,_ range:String?=nil,_ etag:String?=nil,_ cap:Int)throws->CourierHTTPS.Response {
        _=try device(ref);try require(try store.number("SELECT repair FROM courier_pairs WHERE ref=?",[ref])==0,"REPAIR_REQUIRED");guard var token=try secrets.readNative(store.text("SELECT credential FROM courier_pairs WHERE ref=?",[ref])),token.count==43 else { throw CourierError("CREDENTIAL_UNAVAILABLE") };defer { token.resetBytes(in:0..<token.count) };let epoch=https.epoch()
        for attempt in 0..<3 { try https.check(epoch);let r=try https.request(path,store.text("SELECT pin FROM courier_pairs WHERE ref=?",[ref]),token,post,range,etag,cap);if r.status<400 { return r };let error=try CourierWire.json(r.body,512);try CourierWire.keys(error,"error");let code=CourierWire.remoteError(try CourierWire.string(error,"error"))
            if (r.status==401 && ["AUTH_REQUIRED","INVALID_TOKEN"].contains(code)) || (r.status==403 && code=="TOKEN_REVOKED") { try store.transaction { try store.run("UPDATE courier_pairs SET repair=1 WHERE ref=?",[ref]) };throw CourierError("REPAIR_REQUIRED") }
            if r.status==503 && r.header("retry-after")=="1" && attempt<2 { for _ in 0..<10 { try https.check(epoch);Thread.sleep(forTimeInterval:0.1) };continue };throw CourierError(r.status==503 ? "RETRYABLE_503":code)
        };throw CourierError("RETRY_BUDGET")
    }
    func detail(_ ref:String,_ session:String)throws->[String:Any] { try require(CourierWire.match(session,"[0-9a-f]{32}"),"SESSION");let r=try request(ref,"/api/v1/flights/"+session,nil,nil,nil,2048);try require(r.status==200,"DETAIL_STATUS");let m=try CourierWire.metadata(CourierWire.json(r.body,2048),device(ref),true);try require(try CourierWire.string(m,"session_id")==session && CourierWire.etag(m)==r.header("etag"),"DETAIL_IDENTITY");_=try CourierWire.identity(m);validatedPeer=ref+"|"+(try store.text("SELECT pin FROM courier_pairs WHERE ref=?",[ref]));return m }
    func dispatch(_ op:String,_ o:[String:Any],_ packaged:Bool)throws->[String:Any] {
        try CourierWire.keys(o,op=="courierCancel" ? "":op=="courierDetail" || op=="courierDownload" ? "paired_ref session_id":"paired_ref")
        if op=="courierCancel" { https.cancel();return ["state":"CANCELLED"] };let ref=try CourierWire.string(o,"paired_ref"),d=try device(ref)
        if op=="courierConnection" { return ["source_device_id":d,"state":try store.number("SELECT repair FROM courier_pairs WHERE ref=?",[ref])==1 ? "REPAIR_REQUIRED":"PAIRED","FULL_ACK_GATE_PASS":try fullGate(ref,packaged),"trust_profile":CourierHTTPS.profile] }
        if op=="courierList" { return try enumerate(ref,d) }
        if op=="courierDetail" { return try detail(ref,CourierWire.string(o,"session_id")) }
        if op=="courierDownload" { return try download(ref,CourierWire.string(o,"session_id"),packaged) }
        if op=="courierRetryAcks" { return try retry(ref,packaged) };throw CourierError("UNKNOWN_OPERATION")
    }
    func enumerate(_ ref:String,_ d:String)throws->[String:Any] { let epoch=https.epoch();for restart in 0..<3 { var all=[[String:Any]](),seen=Set<String>(),cursors=Set<String>(),cursor:String?,generation:UInt64?,count:UInt64?
        do { for _ in 0..<8 { try https.check(epoch);let path="/api/v1/flights?limit=8"+(cursor.map { "&cursor="+$0 } ?? "");let r=try request(ref,path,nil,nil,nil,16384);try require(r.status==200,"LIST_STATUS");let page=try CourierWire.list(r.body,d),g=try CourierWire.uint(page,"manifest_generation",0xffffffff),c=try CourierWire.uint(page,"count",64);if generation==nil { generation=g;count=c };try require(generation==g && count==c,"LIST_SNAPSHOT_CHANGED");let rows=page["entries"] as! [[String:Any]];for m in rows { let key=(m["session_id"] as? String) ?? "filename:"+(m["filename"] as! String);try require(seen.insert(key).inserted,"DUPLICATE_SESSION");all.append(m) };if page["next_cursor"] is NSNull { try require(UInt64(all.count)==count,"LIST_COUNT");validatedPeer=ref+"|"+(try store.text("SELECT pin FROM courier_pairs WHERE ref=?",[ref]));return ["entries":all,"manifest_generation":g,"source_device_id":d] };cursor=try CourierWire.string(page,"next_cursor");try require(cursors.insert(cursor!).inserted && rows.count==8,"CURSOR_LOOP") };throw CourierError("PAGE_BUDGET") }
        catch let error as CourierError { if error.code != "CURSOR_STALE" || restart==2 { throw error } }
    };throw CourierError("CURSOR_RETRY_BUDGET") }
    func phase(_ e:String,_ value:String)throws { var status=try store.status(e);status["state"]=value;progress?(status) }
    func conflict(_ e:String)throws { try store.transaction { try store.run("UPDATE downloads SET state='SOURCE_CHANGED' WHERE e=?",[e]) } }
    func download(_ ref:String,_ session:String,_ packaged:Bool,_ approved:String?=nil)throws->[String:Any] {
        let epoch=https.epoch();try require(CourierWire.match(session,"[0-9a-f]{32}"),"SESSION");let existing=try store.text("SELECT e FROM downloads WHERE s=? LIMIT 1",[device(ref)+"|"+session]);if !existing.isEmpty { try store.reopen();try store.revalidateCommitted(existing);try require(try store.text("SELECT state FROM downloads WHERE e=?",[existing]) != "SOURCE_CHANGED","SOURCE_CHANGED") };let m=try detail(ref,session);let d=try device(ref),sha=try CourierWire.string(m,"metadata_sha256"),s=d+"|"+session,e=s+"|"+sha,identity=try CourierWire.identity(m),size=try EvidenceVerifier.physical(identity)
        let prior=try store.text("SELECT e FROM downloads WHERE s=? AND e!=? LIMIT 1",[s,e]);if !prior.isEmpty { try conflict(prior);throw CourierError("SOURCE_CHANGED") }
        try require(try CourierWire.automatic(m) || (approved==sha && ownerSelectable(m)),"OWNER_SELECTION_REQUIRED");let saved=try store.text("SELECT detail FROM courier_remote WHERE e=?",[e]);if !saved.isEmpty { let old=try CourierWire.json(Data(saved.utf8),2048);for k in ["session_id","physical_sha256","physical_bytes","metadata_sha256"] { if try CourierWire.string(old,k) != CourierWire.string(m,k) { try conflict(e);throw CourierError("SOURCE_CHANGED") } };try store.reopen();try store.revalidateCommitted(e) }
        else { try store.transaction { try store.run("INSERT OR IGNORE INTO downloads(e,s,metadata) VALUES(?,?,?)",[e,s,identity]);try require(try store.metadata(e)==identity,"DUPLICATE_METADATA");try store.run("INSERT INTO courier_remote(e,detail) VALUES(?,?)",[e,String(data:try JSONSerialization.data(withJSONObject:m),encoding:.utf8)!]) } }
        try require(try store.number("SELECT count(*) FROM downloads WHERE s=?",[s])==1 && store.text("SELECT state FROM downloads WHERE e=?",[e]) != "SOURCE_CHANGED","SOURCE_CHANGED")
        while try store.number("SELECT offset FROM downloads WHERE e=?",[e])<size { try https.check(epoch);let start=try store.number("SELECT offset FROM downloads WHERE e=?",[e]),end=min(start+16384,size)-1;let r:CourierHTTPS.Response
            do { r=try request(ref,"/api/v1/flights/"+session+"/evidence",nil,"bytes=\(start)-\(end)",CourierWire.etag(m),16384) }
            catch let error as CourierError { if error.code=="EVIDENCE_CHANGED" { try conflict(e);_=try? detail(ref,session);throw CourierError("SOURCE_CHANGED") };throw error }
            try require(try r.status==206 && r.header("content-length")==String(end-start+1) && r.header("content-range")=="bytes \(start)-\(end)/\(size)" && r.header("etag")==CourierWire.etag(m) && r.header("accept-ranges")=="bytes" && Int64(r.body.count)==end-start+1,"RANGE_RESPONSE");try https.check(epoch);try store.commitNative(e,start,r.body);progress?(try store.status(e))
        }
        try phase(e,"STORED_LOCAL");try phase(e,"VERIFYING");try store.reopen();try store.verify(e);try https.check(epoch);try store.transaction { try store.run("INSERT OR IGNORE INTO flights(e,s) SELECT e,s FROM downloads WHERE e=?",[e]);try store.run("UPDATE downloads SET state='IMPORTED' WHERE e=?",[e]) };try store.reopen();try store.verify(e);try require(try store.qualification(packaged)["LOCAL_STORAGE_GATE_PASS"] as? Bool==true,"LOCAL_GATE_DENIED");let ack=try CourierWire.ack(store.metadata(e),sha),request=String(data:try JSONSerialization.data(withJSONObject:ack),encoding:.utf8)!;try store.transaction { try store.run("INSERT OR IGNORE INTO courier_ack(e,device,request,state) VALUES(?,?,?,'PENDING')",[e,d,request]);try store.run("UPDATE flights SET ack_status=(SELECT state FROM courier_ack WHERE e=?) WHERE e=?",[e,e]) };return try store.status(e)
    }
    func fullGate(_ ref:String,_ packaged:Bool)throws->Bool { try store.number("SELECT repair FROM courier_pairs WHERE ref=?",[ref])==0 && secrets.exists(store.text("SELECT credential FROM courier_pairs WHERE ref=?",[ref])) && CourierQualification.full(store,packaged,validatedPeer==ref+"|"+store.text("SELECT pin FROM courier_pairs WHERE ref=?",[ref])) }
    func retry(_ ref:String,_ packaged:Bool)throws->[String:Any] { let epoch=https.epoch();try https.check(epoch);_=try device(ref);try require(try fullGate(ref,packaged),"MOBILE_QUALIFICATION_REQUIRED")
        try require(try store.qualification(packaged)["LOCAL_STORAGE_GATE_PASS"] as? Bool==true,"LOCAL_GATE_DENIED");let pending=try store.rows("SELECT e FROM courier_ack WHERE device=? AND state!='ACKED' ORDER BY e LIMIT 64",[device(ref)])
        for row in pending { try https.check(epoch);let e=row[0] as! String;try store.reopen();try store.verify(e);let persistedRequest=Data(try store.text("SELECT request FROM courier_ack WHERE e=?",[e]).utf8);let ack=try CourierWire.json(persistedRequest,1024),expected=try CourierWire.ack(store.metadata(e),String(e.suffix(64)));try require(NSDictionary(dictionary:ack).isEqual(to:expected),"OUTBOX_IDENTITY");try store.transaction { try store.run("UPDATE courier_ack SET state='OUTCOME_UNKNOWN' WHERE e=?",[e]) };let r=try request(ref,"/api/v1/flights/"+CourierWire.string(ack,"session_id")+"/ack",persistedRequest,nil,nil,1024);try require(r.status==200,"ACK_STATUS");try CourierWire.ackResult(r.body,ack);try store.transaction { try store.run("UPDATE courier_ack SET state='ACKED' WHERE e=?",[e]);try store.run("UPDATE flights SET ack_status='ACKED' WHERE e=?",[e]) } };return ["state":"ACK_RETRY_COMPLETE"]
    }
}
